services:
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.1-0  # multi-arch tag
    container_name: keycloak
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    platform: linux/amd64   # force emulation if needed